---
- hosts: cluster_nodes
  remote_user: root
  gather_facts: no

  tasks:
  - name: Copy the public key from local to remote
    copy: src=/tmp/playbooks/{{ item }}/var/lib/glusterd/nfs/secret.pem.pub
          dest=/tmp/key
    with_items: groups['cluster_nodes']

  - name: Deploy the pubkey ~/root/.ssh/authorized_keys on all nodes
    shell: cat /tmp/key >> ~/.ssh/authorized_keys

  - name: Remove the unwanted copy of key
    shell: rm -rf ~/tmp/key
