---
- hosts: georep_master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Generate a common pem pub file
    shell: "gluster system:: execute gsec_create"


  - name: Create the geo-rep session
    georep: action=create
            mastervol="{{ mastervolname }}"
            slavevol="{{ slavevol }}"
            force="{{ force }}"

  - name: Create the geo-rep session
    georep: action=start
            mastervol="{{ mastervolname }}"
            slavevol="{{ slavevol }}"
            force="{{ force }}"
