---
- hosts: georep_master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Starts the geo-rep session
    georep: action=start
            mastervol="{{ mastervolname }}"
            slavevol="{{ slavevol }}"
            force="{{ force }}"
