---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Rebalance an existing volume
    volume:  action=rebalance
             volume="{{ volname }}"
             state="{{ state }}"
             force=yes
