---
- hosts: master_node
  remote_user: root
  gather_facts: no

  - name: Export volume through NFS-Ganesha
    volume-set: action=set
                volume="{{ volname }}"
                key=ganesha.enable
                value=on
