---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
  - name: Create the backend disks, fails if present
    shell: mkdir -p {{ item.path }}
    with_items: mntpath

  - name: Mount the volumes
    mount: name={{ item.path }} src={{ item.device }} fstype=xfs
           opts="inode64,noatime,nodiratime" state=mounted

    with_items: mntpath
