---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
  # Create pv on all the disks
  - name: Create Physical Volume on all the nodes
    pv: action=create disks="{{ bricks }}"
        options="--dataalignment {{ dalign }}k"
