---
- hosts: cluster_nodes
  remote_user: root
  gather_facts: no

  tasks:
  - name: Create a user hacluster in all the cluster nodes if not already present
    user: name=hacluster

  - name: Set the hacluster user the same password on all machines
    shell: echo hacluster | passwd --stdin hacluster

