---
- include: gluster-snapshot-delete.yml
- include: client_volume_umount.yml
- include: gluster-volume-delete.yml
- include: gluster-peer-detach.yml
- include: umount.yml
- include: lvremove.yml
- include: vgremove.yml
- include: pvremove.yml
