---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
  - name: Add/Delete services to firewalld rules
    firewalld: service={{ item }} permanent="{{ permanent }}" state="{{ firewall_state }}"
               zone="{{ zone }}"
    with_items: services

  - name: Reloads firewalld
    shell: firewall-cmd --reload
