---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
  - name: Create an xfs filesystem
    command: mkfs.xfs {{ opts }} {{ item }}
#    filesystem: fstype="{{ fstype }}" dev={{ item }}
#                opts="{{ opts }}"
    with_items: "{{ lvols }}"
