---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
  - name: Create a xfs filesystem
    filesystem: fstype="{{ fstype }}" dev={{ item }}
                opts="{{ opts }}"
    with_items: "{{ lvols }}"
