---
- hosts: master
  remote_user: root
  gather_facts: no
  vars:
    ganesha_export_conf: exports/export.ganesha.conf

  tasks:

  - name: Delete lines from Ganesha export file
    lineinfile:
        dest="{{ ha_base_dir }}/{{ ganesha_export_conf }}"
        regexp="{{ item }}"
        state=absent
    with_items: "{{ del_config_lines | default([]) }}"
    when: del_config_lines is defined

  - name: Add lines to Ganesha export file
    lineinfile:
        dest="{{ ha_base_dir }}/{{ ganesha_export_conf }}"
        line="{{ item }}"
        insertbefore="}"
    with_items: "{{ add_config_lines | default([]) }}"
    when: add_config_lines is defined

  # Use blockinfile when all the channles are updated with ansible 2.x
  # Using lineinfile for now.
  - name: Add a block to Ganesha export file
    lineinfile:
        dest="{{ ha_base_dir }}/{{ ganesha_export_conf }}"
        line="{{ item }}"
        insertbefore="}"
        state=present
    with_items: "{{ config_block | default([]) }}"
    when: config_block is defined

  - name: Refresh NFS-Ganesha config
    shell: /usr/libexec/ganesha/ganesha-ha.sh --refresh-config "{{ ha_base_dir }}" "{{ volname }}"
