---
- hosts: master_node
  remote_user: root
  gather_facts: no

  tasks:
  - name: Disable gluster.nfs
    volume_set: action=set
                volume="{{ volname }}"
                key=nfs.disable value=on

