---
- hosts: master_node
  remote_user: root
  gather_facts: no

  tasks:
  - name: Generate ssh key in one of the nodes in HA cluster
    shell: echo -e  'y\n'|ssh-keygen -q -t rsa -N "" -f /var/lib/glusterd/nfs/secret.pem

  - name: Copy the public key to the local
    fetch: src=/var/lib/glusterd/nfs/secret.pem.pub
           dest="{{ base_dir }}"

  - name: Copy the private key to the local
    fetch: src=/var/lib/glusterd/nfs/secret.pem
           dest="{{ base_dir }}"
