---
- hosts: georep_master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Stop the geo-rep session
    georep: action=stop
            mastervol="{{ mastervolname }}"
            slavevol="{{ slavevol }}"
            force="{{ force }}"
