---
- hosts: georep_master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Delete the geo-rep session
    geo_rep: action=delete
            mastervol="{{ mastervolname }}"
            georepuser="{{ georepuser }}"
            slavevol="{{ slavevol }}"

