---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Stops a volume
    volume: action=stop
             volume="{{ volname }}"
    register: result
    failed_when: "result.rc != 0 and ('already stopped' not in result.msg and 'does not exist' not in result.msg)"
    ignore_errors: yes


  - name: Deletes a volume
    volume:  action=delete
             volume="{{ volname }}"
    register: result
    failed_when: "result.rc != 0 and ('does not exist' not in result.msg)"
