---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Clones a snapshot
    snapshot: action=clone
             snapname={{ snapname }}
             clonename={{ clonename }}
             force="{{ force }}"
