---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Rebalance an existing volume
    command: "gluster volume rebalance {{ volname }} {{ state }} {{ force }} "
#    volume:  action=rebalance
#             volume="{{ volname }}"
#             state="{{ state }}"
#             force="{{ force }}"
