---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Gluster volume quota operation
    quota:  action="{{ action }}"
            volume="{{ volname }}"
            path={{ item }}
            percent="{{ percent }}"
            time="{{ time }}"
    with_items: path
