---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Creates a Trusted Storage Pool
    peer: action=probe
          hosts="{{ to_be_probed }}"
          current_host={{inventory_hostname}}

  - name: Pause for some seconds
    pause: seconds=5
