---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Gluster volume quota limit size operation
    quota:  action="{{ action }}"
            volume="{{ volname }}"
            path={{ item.path }}
            size={{ item.size }}
    with_items: limits
