---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Starts a volume
    volume:  action=start volume="{{ volname }}"
             force="{{ force | default(False) }}"
    register: result
    ignore_errors: yes
