---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Replace a brick in volume
    command: "gluster volume replace-brick {{ volname }} {{ bricks[0] }} {{ bricks[1] }} commit force"
#    volume:  action=replace-brick
#             volume="{{ volname }}"
#             bricks="{{ bricks }}"
