---
- hosts: fuse_clients
  remote_user: root
  gather_facts: no

  tasks:
  - name: Create the dir to mount the volume, skips if present
    shell: mkdir {{ item }} -p

    with_items: client_mount_points

  - name: Mount the volumes
    mount: name={{ item }}
           src="{{ groups['master'][0]}}:{{ volname }}"
           fstype="{{ fstype }}"
           state=mounted

    with_items: client_mount_points

