---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Starts a volume
    volume:  action=start volume="{{ volname }}"
             force="{{ force }}"
    register: result
    failed_when: "result.rc != 0 and 'already started' not in result.msg"
