---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
  - name: Activates a snapshot
    snapshot: action=activate
             snapname="{{ snapname }}"
             force="{{ force }}"
