---
- hosts: cifs_clients
  remote_user: root
  gather_facts: no

  tasks:
  - name: Create the dir to mount the volume, skips if present
    file: path={{ item }} state=directory

    with_items: client_mount_points

  - name: Mount the volumes
    mount: name={{ item }}
           src="\\\\{{ groups['master'][0]}}\\gluster-{{ volname }}"
           fstype="cifs"
           opts="username={{smb_username}},password={{smb_password}}"
           state=mounted

    with_items: client_mount_points

