---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
      - name: Gluster volume quota limit objects operation
    quota:  action="{{ action }}"
            volume="{{ volname }}"
            path={{ item.path }}
            number={{ item.number }}
    with_items: "{{ limits }}"
