---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
      - name: Create LVs with specified size for the VGs
        lvol: lv={{ item.name }} size={{ item.size }} vg="{{ vg}}"
              force="{{ force }}"
        with_items: lvs
