---
- hosts: master
  remote_user: root
  gather_facts: no

  tasks:
   - name: Move the json/yml file to master
     template: src="{{ item.filepath }}" dest=/var/tmp
     with_items: "{{ filelist }}"

   - name: kubectl create pod from json input
     kubectl: action=create filename="/var/tmp/{{ item.filedest }}"
              filetype="{{ filetype }}" variable={{ item.variable }}
     with_items: "{{ filelist }}"

