---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
  - name: start/stop/restart/reload services
    service: name={{ item }} state="{{ state }}"
    with_items: "{{ service }}"

