---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:

  - name: Creates /etc/ctdb directory
    file: path=/etc/ctdb state=directory

  - name: Clean up /etc/sysconfig/ctdb
    file: path=/etc/sysconfig/ctdb state=absent

  - name: Clean up /etc/ctdb/nodes
    file: path=/etc/ctdb/nodes state=absent

  - name: Clean /etc/ctdb/public_addresses
    file: path=/etc/ctdb/public_addresses state=absent

  - name: Create /etc/sysconfig/ctdb
    file: path=/etc/sysconfig/ctdb state=touch

  - name: Create /etc/ctdb/nodes
    file: path=/etc/ctdb/nodes state=touch

  - name: Create /etc/ctdb/public_addresses
    file: path=/etc/ctdb/public_addresses state=touch

  - name: Add confs to /etc/sysconfig/ctdb
    lineinfile: dest=/etc/sysconfig/ctdb
                line="{{ options }}"
    when: options is defined

  - name: Add confs to /etc/ctdb/nodes
    lineinfile: dest=/etc/ctdb/nodes
                line="{{ nodes }}"
    when: nodes is defined

  - name: Add confs to /etc/ctdb/public_addresses
    lineinfile: dest=/etc/ctdb/public_addresses
                line="{{ paddress }}"
    when: paddress is defined
