---
# Implementation adopted from https://github.com/ceph/ceph-cm-ansible/blob/master/roles/common/tasks/rhel-entitlements.yml

- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
  - name:  Register
    redhat_subscription: state=present
                         pool=8a85f98148751d4301488e7352f725e6
