---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no

  tasks:
      - name: Create LVs with specified size for the VGs
        command: lvcreate --thinpool {{ item.pool }} -V {{ item.virtualsize }} -n {{ item.lv }} {{ item.vg }}
#        lv: action=create lvtype="{{ lvtype }}" lvname={{ item.lv }}
#            virtualsize={{ item.virtualsize }} vgname={{ item.vg }}
#              poolname={{ item.pool }}
        with_items: "{{ lvnamelist }}"
