---
- hosts: gluster_servers
  remote_user: root
  gather_facts: no       # For now do not gather facts, but would like to gather
                         # facts and use the disks from gathered facts

  tasks:
  - name: Remove the volume groups
    vg: action="remove"
        vgname="{{ vgs }}"
